name: sink
description: Easily verify that you&#x27;re spending more than you can afford

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0+8
  cloud_firestore: ^0.12.9
  firebase_auth: ^0.15.3+1
  google_sign_in: ^4.0.4
  flutter_redux: ^0.6.0
  flutter_circular_chart: ^0.1.0
  font_awesome_flutter: ^8.4.0
  intl: ^0.15.8
  uuid: ^1.0.3
  quiver: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.5.1

flutter:
  uses-material-design: true
